---
settings:
  name: BlueXP
  platform: cloud
  search: bluexp-relnotes,bluexp-setup-admin,bluexp-cloud-volumes-ontap,bluexp-ontap-onprem,bluexp-azure-netapp-files,bluexp-fsx-ontap,bluexp-cloud-volumes-service-gcp,bluexp-kubernetes,bluexp-remediation,bluexp-backup-recovery,bluexp-copy-sync,bluexp-classification,bluexp-tiering,bluexp-ransomware-protection,bluexp-replication,bluexp-edge-caching,bluexp-cloud-ops,bluexp-automation,cloud-volumes-ontap-relnotes,bluexp-storagegrid,bluexp-e-series,bluexp-s3-storage,bluexp-economic-efficiency,bluexp-operational-resiliency,bluexp-digital-wallet
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: BlueXPのすべてのマニュアル
    url: "/index.html"
product-family:
  sidebarlinks:
  - title: すべて
    tags: all
    class: active
  - title: API
    tags: api
  - title: コネクタとアカウント
    tags: admin
  - title: 拡張子
    tags: extension
  - title: ガバナンス
    tags: governance
  - title: 健常性
    tags: health
  - title: モビリティ
    tags: mobility
  - title: 保護
    tags: protection
  - title: ストレージ
    tags: storage
  tiles:
  - title: BlueXPへようこそ
    icon: "./media/icon-docs.png"
    url: concept-overview.html
    summary: BlueXPの概要について説明します。
    tags: all
  - title: セットアップと管理
    icon: "./media/icon-admin.png"
    url: https://docs.netapp.com/us-en/bluexp-setup-admin/index.html
    summary: BlueXPの使用を開始し、コネクタやアカウントなどを管理する方法について説明します。
    tags: all,admin
  - title: リリースノート
    icon: "./media/icon-docs.png"
    url: https://docs.netapp.com/us-en/bluexp-relnotes/index.html
    summary: BlueXPのすべての新機能について説明します。
    tags: all
  - title: NetApp ONTAP 対応の Amazon FSX
    icon: "./media/icon-fsx.png"
    url: https://docs.netapp.com/us-en/bluexp-fsx-ontap/index.html
    summary: AWS が管理する標準サービスとして、 ONTAP の全機能を使用できます。
    tags: all,storage,aws
  - title: Amazon S3ストレージ
    icon: "./media/icon-s3.png"
    url: https://docs.netapp.com/us-en/bluexp-s3-storage/index.html
    summary: AWSアカウント内のAmazon S3バケットを検出して管理します。
    tags: all,storage,aws
  - title: API
    icon: "./media/icon-api.png"
    url: https://docs.netapp.com/us-en/bluexp-automation/index.html
    summary: クラウドベースのリソースをプログラムで管理できます。
    tags: all,api
  - title: Azure BLOBストレージ
    icon: "./media/icon-azure-blob.png"
    url: https://docs.netapp.com/us-en/bluexp-blob-storage/index.html
    summary: AzureサブスクリプションでAzure BLOBストレージを検出および管理します。
    tags: all,storage
  - title: Azure NetApp Files の特長
    icon: "./media/icon-anf.png"
    url: https://docs.netapp.com/us-en/bluexp-azure-netapp-files/index.html
    summary: コアビジネスアプリケーション向けのハイパフォーマンスなファイルストレージサービス。
    tags: all,storage,azure
  - title: バックアップとリカバリ（Cloud Backup）
    icon: "./media/icon-backup.png"
    url: https://docs.netapp.com/us-en/bluexp-backup-recovery/index.html
    summary: クラウドとオンプレミスのデータをバックアップ、リストア
    tags: all,aws,azure,gcp,protection
  - title: 分類（Cloud Data Sense）
    icon: "./media/icon-data-sense.png"
    url: https://docs.netapp.com/us-en/bluexp-classification/index.html
    summary: アプリケーションデータとクラウド環境のプライバシーを確保
    tags: all,governance,aws,azure,gcp
  - title: クラウド運用（コンピューティング）
    icon: "./media/icon-compute.png"
    url: https://docs.netapp.com/us-en/bluexp-cloud-ops/index.html
    summary: クラウドコンピューティング関連の支出を可視化し、削減可能なコストを特定できます。
    tags: all,aws,extension
  - title: Cloud Volumes ONTAP
    icon: "./media/icon-cvo.png"
    url: https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html
    summary: クラウドストレージを低コストでインテリジェントに、コンプライアンスに準拠し、セキュアに構築できます。
    tags: all,storage,aws,azure,gcp
  - title: Cloud Volumes Service for Google Cloud
    icon: "./media/icon-cvs.png"
    url: https://docs.netapp.com/us-en/bluexp-cloud-volumes-service-gcp/index.html
    summary: ファイルストレージをセキュアに、保護、高速化します。
    tags: all,storage,gcp
  - title: コピーと同期（Cloud Sync ）
    icon: "./media/icon-sync.png"
    url: https://docs.netapp.com/us-en/bluexp-copy-sync/index.html
    summary: オンプレミスとクラウドのデータストア間でデータを同期
    tags: all,aws,azure,gcp,mobility
  - title: デジタルアドバイザ（Active IQ ）
    icon: "./media/icon-activeiq.png"
    url: https://docs.netapp.com/us-en/active-iq/index.html
    tags: all,health
    summary: 実用的な情報でストレージの健常性を最適化
  - title: デジタルウォレット
    icon: "./media/digital-wallet.png"
    url: https://docs.netapp.com/us-en/bluexp-digital-wallet/index.html
    tags: all,governance
    summary: ライセンスとサブスクリプションを管理および監視します。
  - title: Eシリーズシステム
    icon: "./media/icon-e-series.png"
    url: https://docs.netapp.com/us-en/bluexp-e-series/index.html
    summary: ハイブリッドマルチクラウド全体のデータを包括的に把握できるEシリーズシステムをご紹介します。
    tags: all,storage
  - title: 経済効率
    icon: "./media/icon-economic-efficiency.png"
    url: https://docs.netapp.com/us-en/bluexp-economic-efficiency/index.html
    summary: 現在または予測されている低容量のクラスタを特定し、データ階層化または容量追加の推奨事項を実装します。
    tags: all,governance
  - title: エッジキャッシング（Global File Cache）
    icon: "./media/icon-cache.png"
    url: https://docs.netapp.com/us-en/bluexp-edge-caching/index.html
    summary: 分散した従業員にリアルタイムのグローバルファイル共有を提供します。
    tags: all,mobility,aws,azure,gcp
  - title: Kubernetes クラスタ
    icon: "./media/icon-kubernetes.png"
    url: https://docs.netapp.com/us-en/bluexp-kubernetes/index.html
    summary: ハイブリッドクラウド内の Kubernetes クラスタの高度なデータ管理。
    tags: all,storage,aws,azure
  - title: 移行レポート
    icon: "./media/icon-reports.png"
    url: https://docs.netapp.com/us-en/bluexp-reports/index.html
    summary: ストレージ環境のファイル数、ファイルシステムツリーの深さと幅、大容量ファイルなどを特定します。
    tags: all,storage
  - title: オンプレミスの ONTAP クラスタ
    icon: "./media/icon-onprem.png"
    url: https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html
    summary: System ManagerとBlueXPのデータサービスを使用して、AFF システムとFAS システムをBlueXPから管理できます。
    tags: all,storage
  - title: 運用の耐障害性
    icon: "./media/icon-op-resiliency.png"
    url: https://docs.netapp.com/us-en/bluexp-operational-resiliency/index.html
    summary: ファームウェアとソフトウェア設定のリスクを自動で修正し、ONTAP クラスタの健全性を維持
    tags: all,health
  - title: ランサムウェアからの保護
    icon: "./media/icon-ransomware.png"
    url: https://docs.netapp.com/us-en/bluexp-ransomware-protection/index.html
    summary: サイバー攻撃に対するデータの復元力を評価します。
    tags: all,governance,protection
  - title: 修正（AppTemplate）
    icon: "./media/icon-app-template.png"
    url: https://docs.netapp.com/us-en/bluexp-remediation/index.html
    summary: BlueXPのアクションを自動化して、プロビジョニングを高速化し、手動作業を排除します。
    tags: all,health
  - title: レプリケーション
    icon: "./media/icon-replication.png"
    url: https://docs.netapp.com/us-en/bluexp-replication/index.html
    summary: バックアップとディザスタリカバリをサポートするために、ストレージシステム間でデータをレプリケートします。
    tags: all,protection
  - title: StorageGRID
    icon: "./media/icon-storagegrid.png"
    url: https://docs.netapp.com/us-en/bluexp-storagegrid/index.html
    summary: StorageGRID システムの検出と管理
    tags: all,storage
  - title: 階層化（Cloud Tiering）
    icon: "./media/icon-tiering.png"
    url: https://docs.netapp.com/us-en/bluexp-tiering/index.html
    summary: オンプレミスの ONTAP ストレージをクラウドに拡張
    tags: all,aws,azure,gcp,mobility
  - title: ボリュームキャッシュ
    icon: "./media/icon-docs.png"
    url: https://docs.netapp.com/us-en/bluexp-volume-caching/index.html
    summary: 書き込み可能なキャッシュボリュームを作成して、データへのアクセスを高速化したり、アクセス頻度の高いボリュームのトラフィックをオフロードしたりします。
    tags: all,mobility
